### PR TITLE
add support for virtual path remapping

### PR DESCRIPTION
**Pull request by erique**

### CODE REVIEW

**Comment by erique** [comment]
this is needed to support the virtual paths within the package manager..

**Comment by joshpeterson** [comment]
Do we need this same change in the new Mono as well? And should we try to upstream this?

**Comment by erique** [comment]
@joshpeterson Yes, and yes. Though I'm not sure how cleanly it will apply to 4.8..

**Comment by joshpeterson** [comment]
We will probably need to make the change manually to the unity-mono-4.8.0-branch. I don't think it will cherry-pick. We'll also need to make the change to a branch of master to upstream it.

Can we write unit tests for this in C#? That might help to make sure we get it in the newer branches correctly.

**Comment by erique** [comment]
@joshpeterson I'm not sure we want/need to upstream it though..

**Comment by joshpeterson** [comment]
Yeah, I guess that is always a trade-off. Anything we don't upstream we need to merge when we update Mono in the future. I suggest that we try to upstream it, if only to make our lives easier in the future.

**Pull request merged**
