### PR TITLE
[aot] Fix mono AOT code generation

### PR DESCRIPTION
**Pull request by zsaladin**
- System.Linq.FirstOrDefault
- System.Linq.Last
- System.Linq.LastOrDefault
- System.Linq.Single
- System.Linq.SingleOrDefault

link : https://github.com/mono/mono/blob/mono-3-2/mcs/class/System.Core/System.Linq/Enumerable.cs

### CODE REVIEW

**Comment by joshpeterson** [comment]
Thanks for this submission. Can you provide more details about the problem this is solving? Specifically, is there a bit of C# code that fails here with Mono-AOT?

**Comment by zsaladin** [comment]
These codes will fail on iOS with Mono-AOT.

int[] numbers = new int[] { 0 };
numbers.FirstOrDefault(); // fail
numbers.Last(); // fail
numbers.LastOrDefault(); // fail
numbers.Single(); // fail
numbers.SingleOrDefault(); //fail

These above methods throw same exceptions.

ExecutionEngineException: Attempting to JIT compile method 'System.Linq.Enumerable/PredicateOf`1<int>:.cctor ()' while running with --aot-only.

They use 'PredicateOf<TSource>.Always' internally.
It happens if value type is located at 'TSource' as generic type parameter.
In this case 'TSource' is 'int'.
Maybe it occurs because of Mono-AOT Limitations.

**Comment by joshpeterson** [comment]
These changes look good, thanks. I'm going to build a test case on our side to confirm this. In order to take the changes, we need to license them as MIT/X11. Do you agree to do that?

**Comment by zsaladin** [comment]
Yes, I agree if there is no license issue with the mono 3.2 codes.

**Comment by joshpeterson** [comment]
The Mono 3.2 code is MIT/X11 as well, so this should be fine. Thanks! We will take this patch.

**Pull request merged**
