### PR TITLE
Merge latest changes from unity-staging to unity-trunk

### PR DESCRIPTION
**Pull request by joshpeterson**

### CODE REVIEW

**Comment by joshpeterson** [comment]
@davidrogers-unity Please confirm that I've correctly merged the conflict in the `build_runtime_tizen.sh` file.

**Comment by davidrogers-unity** [comment]
As far as I can tell, unless I'm looking in the wrong place, none of the tizen changes are included.

**Comment by joshpeterson** [comment]
@davidrogers-unity That sounds good then, as it means I've merged correctly with the changes from unity-trunk. Thanks!

**Comment by joshpeterson** [comment]
Actually, Jon pointed out that I may have been incorrect, and taken a change from unity-trunk instead of the one you committed to unity-staging. I'll try to correct it now.

**Comment by joshpeterson** [comment]
Ok, now the PR has the changes to external/buildscripts/build_runtime_tizen.sh. Please confirm that they are correct.

**Comment by davidrogers-unity** [comment]
I'm not sure why but I don't see all of the changes from this PR.

https://github.com/Unity-Technologies/mono/pull/370/files

**Comment by joshpeterson** [comment]
I think that those changes are already in unity-trunk from https://github.com/Unity-Technologies/mono/pull/367

**Comment by davidrogers-unity** [comment]
Oh ok

**Pull request merged**
