### PR TITLE
Avoid stubbing CustomMarshalInfo (UUM-21101)

### PR DESCRIPTION
**Pull request by joshpeterson**
This profile stubber will avoid stubbing CustomMarshalIntfo at all.

In a previous PR:

https://github.com/Unity-Technologies/mono/pull/1711

we attempted to properly stub the CustomMarshalInfo, but we found it was better to simply avoid stubbing it.

- Should this pull request have release notes?
  - [ ] Yes
  - [x] No
- Do these changes need to be back ported?
  - [ ] Yes
  - [x] No
- Do these changes need to be upstreamed to [mono/mono](https://github.com/mono/mono) or [dotnet/runtime](https://github.com/dotnet/runtime) repositories?
  - [ ] Yes
  - [x] No

Reviewers: please consider these questions as well! :heart:

### CODE REVIEW

**Comment by joshpeterson** [comment]
I've confirmed these changes work in the IL2CPP repo with all of the tests there as well.

**Review by UnityAlex — COMMENTED** [review]
Need to promote to unity-internal again.

**Comment by joshpeterson** [comment]
> Need to promote to unity-internal again.

Thanks!

**Comment by joshpeterson** [comment]
The code is using unity-internal now.

**Review by UnityAlex — APPROVED** [review]
Thanks for fixing that!

**Pull request merged**
