### PR TITLE
Fixup dllmap for MonoPosixHelper

### PR DESCRIPTION
**Pull request by Tak**
Ran ABV ( https://katana.bf.unity3d.com/projects/Unity/builders/proj0-ABuildVerification/builds/52090?unity_branch=fixes/levi/mbe-monoposixhelper ) plus Linux editor runtime tests with 4.6 and 2.0 standard

### CODE REVIEW

**Comment by joncham** [comment]
Please run runtime tests with new runtime. We had issues with this code before...

**Comment by joncham** [comment]
At least for Editor. Like:
```
Test RuntimeTests - Mac64Editor (New Scripting Runtime - 4.6 profile)
Test RuntimeTests - Windows64Editor (New Scripting Runtime - 4.6 profile)
Test RegressionRuntimeTests - Mac64Editor (New Scripting Runtime)
Test RegressionRuntimeTests - Windows64Editor (New Scripting Runtime - 4.6 profile)
```

**Comment by Tak** [comment]
I ran a bunch of the new scripting runtime stuff on `fixes/levi/mbe-monoposixhelper`
The stable stuff is still passing (and the GZip tests are fixed on linux editor), and the unstable stuff doesn't seem to be affected by this.

**Comment by joncham** [comment]
Does things still work with standalone mono (outside of unity) when using mono posix helper on OSX? I think that's what the path was initially specified.

**Comment by Tak** [comment]
Uh, do we have a test case for that? Isn't it exercised by gfx test runner or one of those?

**Pull request merged**
