### PR TITLE
Implement marshaling for generic struct fields (case 1106422)

### PR DESCRIPTION
**Pull request by joncham**

### CODE REVIEW

**Comment by joshpeterson** [comment]
Can we add a test case for this issue? We might want to upstream it. Also, we should add release notes to the PR description.

**Comment by brianradunity** [comment]
I think I still have mono test code for this case

**Comment by joncham** [comment]
Upstream here: https://github.com/mono/mono/pull/12660

Will add test for upstream. Do we want/need test in our mono?

**Comment by joshpeterson** [comment]
I don't think a test on our end it too important. We'll get that test when we merge anyway.

**Pull request merged**
