### PR TITLE
Added check for managed stack frame

### PR DESCRIPTION
**Pull request by scott-ferguson-unity**
Ensure we have a managed stack frame before access.

### CODE REVIEW

**Review by joncham — APPROVED** [review]

**Comment by joncham** [comment]
@scott-ferguson-unity note this is the file in the Mono repo. There is a copy in the IL2CPP repo.

**Review by UnityAlex — APPROVED** [review]

**Comment by scott-ferguson-unity** [comment]
I assumed everything in `external` in IL2CPP was a submodule and/or stevedore artifact. 

This PR won't hurt anything, but should I take out the case number since landing this won't fix the case?

**Comment by joncham** [comment]
@scott-ferguson-unity case number is fine to leave in.

**Comment by joshpeterson** [comment]
> This PR won't hurt anything, but should I take out the case number since landing this won't fix the case?

Doesn't this correct case 1250002? I confused.

Also, should we back port this fix?

**Comment by scott-ferguson-unity** [comment]
This PR doesn't actually fix 1250002, since the user's issue as a bug in VS2019.  I've landed a fix in the IL2CPP repo for this crash.

Do we need to make the same change here?  Is there any reason to backport it?

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/mono?pullRequest=1298) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/mono?pullRequest=1298) before we can accept your contribution.<br/>**1** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: ashwinimurt<br/>:x: vargaz<br/>:x: thaystg<br/>:x: kumpera<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/mono?pullRequest=1298) it.</sub>

**Pull request closed without merging**
