### PR TITLE
Backport datetime thread safety fixes from upstream

### PR DESCRIPTION
**Pull request by p12tic**
Simple backport for case 657306.

### CODE REVIEW

**Comment by joshpeterson** [comment]
Is it possible to add a test for this case on the Unity side? Maybe we need an iOS integration test here? I'm not sure.

**Comment by joshpeterson** [comment]
Also, I see the back port PR for 5.4 here: https://github.com/Unity-Technologies/mono/pull/380. Should this fix also go to 5.3?

**Comment by joncham** [comment]
LGTM

**Comment by p12tic** [comment]
> Is it possible to add a test for this case on the Unity side? 
It's a race condition. It would be very hard to add a test for the fix.

**Comment by joshpeterson** [comment]
Yes, after Jon explained the bug to me, I agree - it is not easy to add a test for this case.

**Pull request merged**
