### PR TITLE
add MONO_API to fix frame lookup

### PR DESCRIPTION
**Pull request by mderoy**

### CODE REVIEW

**Comment by mderoy** [comment]
@joncham should I go ahead and graft this to our backport branches back to 2017.4? I assume the same problem will be there

**Comment by joncham** [comment]
Is this the only API that needs exposed?

**Comment by joncham** [comment]
Sure, backport through 2017.4 I guess.

**Comment by mderoy** [comment]
@joncham the rest are already exposed.

**Pull request merged**
