### PR TITLE
Add missing facades for Unity profiles (Case 1367105)

### PR DESCRIPTION
**Pull request by bholmes**
Adding to the JIT profiles
 - System.Threading.Tasks.Extensions 
 - System.Xml.XPath.XmlDocument 
 - System.Reflection.DispatchProxy 
 - System.Memory
 - System.Buffers

Used the .Net Standard compat dll list to drive this change.

- Should this pull request have release notes?
  - [X] Yes
  - [ ] No
- Do these changes need to be back ported?
  - [X] Yes
  - [ ] No
- Do these changes need to be upstreamed to [mono/mono](https://github.com/mono/mono) or [dotnet/runtime](https://github.com/dotnet/runtime) repositories?
  - [ ] Yes
  - [X] No

**Release notes**

Fixed case 1367105@bholmes :
Mono: Add missing facade dlls for Unity profiles

**Backports**

 - 2021.2

### CODE REVIEW

**Comment by joshpeterson** [comment]
Once the class library build is complete, I'll confirm that these changes allow the new profile tests in IL2CPP to pass.

**Comment by joncham** [comment]
Why did you decide to not include all the assemblies/subdirs listed in `mobile_only_SUBDIRS`?

**Comment by bholmes** [comment]
> Why did you decide to not include all the assemblies/subdirs listed in `mobile_only_SUBDIRS`?

I did not make a final decision just yet, but I compared this list to the net standard compat profile directory and removed the items that were not there.

**Comment by bholmes** [comment]
I suspect it is better to put the 4 back into the list and use mobile_only_SUBDIRS. My thinking is that these 4 dlls do have NuGets out in universe with implementations. Our class libraries have implementations of these therefore it is best that we provide a facade to direct the code path to our implementation.  IOW revert my last commit. Thoughts?

**Review by joncham — APPROVED** [review]

**Pull request merged**
