### PR TITLE
Fix for race condition in monitor on multicore ARM

### PR DESCRIPTION
**Pull request by hkr**
Missing forward port of https://github.com/Unity-Technologies/mono/pull/247

### CODE REVIEW

**Comment by bitter** [comment]
nice to see fixes got time to mature properly - like a fine aged cheddar

**Comment by joncham** [comment]
Did you test these changes on non-ARM platforms?

**Comment by hkr** [comment]
I checked on Android/x86. The changes are on the 4.6 branch for a while and have shipped for non-ARM platforms.

**Comment by joncham** [comment]
Should these changes go to all the 5.x branches then?

**Comment by hkr** [comment]
yes, should go into all 5.x branches

**Pull request merged**
