### PR TITLE
Avoid a process crash in the debugger with corrupt fields (Case 1323716)

### PR DESCRIPTION
**Pull request by bholmes**
When processing the get values command in the debugger and a field of a
reference type is pointing to a bad memory location, avoid a crash and
instead return ERR_INVALID_OBJECT.

Fixes Case 1323716

- Should this pull request have release notes?
  - [X] Yes
  - [ ] No
- Do these changes need to be back ported?
  - [ ] Yes
  - [X] No
- Do these changes require other changes in the Unity repository?
  - [ ] Yes
  - [X] No

Fix case 1323716:
Mono Runtime: Avoid Unity crash when debugger encounters corrupt data in an object field.

### CODE REVIEW

**Comment by bholmes** [comment]
I should put this in the mono upgrade branch as well.

**Comment by UnityAlex** [comment]
> 
> 
> I should put this in the mono upgrade branch as well.

Yes I was just typing this. May want to poke upstream folks to see if they would want it as well / collect additional feedback.

**Comment by joncham** [comment]
Check is useful, but not precise since it only ensures memory is readable. That prevents initial crash, but the program state is still invalid. I guess I'm wondering how often we will crash (or silently corrupt further) later?

**Comment by bholmes** [comment]
I am holding this PR for now as I have some concerns. There are some performance hits to consider on posix with using a file to check if memory is readable. In addition I found some documentation that states "On GNU/Hurd systems, this error never happens; you get a signal instead." Does this concern us?

> Check is useful, but not precise since it only ensures memory is readable. That prevents initial crash, but the program state is still invalid. I guess I'm wondering how often we will crash (or silently corrupt further) later?

I am just looking for an easy win to help the developer find the corruption opposed to a hard crash. I am no longer convinced this is an easy with because of the potential perf hit.

**Comment by bholmes** [comment]
Deciding against this change due to performance concerns with the debugger.

**Pull request closed without merging**
