### PR TITLE
Fix NetworkInterface.GetAllNetworkInterfaces() on Android

### PR DESCRIPTION
**Pull request by ignas2**
Android uses Linux code path to implement this method. Unfortunately Android doesn't implement getifaddrs/freeifaddrs in libc.so and the method fails. Upstream Mono has this fixed but it's under MONODROID define (which Unity doesn't set). I've backported and adapted the code from https://github.com/xamarin/xamarin-android/tree/master/src/monodroid/jni.

### CODE REVIEW

**Comment by Tak** [comment]
Somebody _actually_ tested this on linux, right? :smile:

**Comment by ignas2** [comment]
This can't possibly not work :) More seriously it should always find getifaddrs/freeifaddrs in libc.so on Linux and behavior wouldn't change in any way. I'll be adding a test that invokes GetAllNetworkInterfaces() on all platforms (including Linux and Android). I'm not sure of the workflow but I'm planning to: merge this pr, build Mono builds.zip, add a test in Unity.

**Comment by joshpeterson** [comment]
The normal workflow for a case like this that carries some risk for a specific platform is to make a builds.zip of Mono on the unity-android-getitfaddrs branch. Then commit that builds.zip to a branch in Unity and run the proper tests locally or on Katana. Once we have confirmed that works, then we will merge this PR to unity-staging.

**Comment by ignas2** [comment]
I did build Mono builds.zip for the branch and tested it locally on Android. I think the risk of this not working on Linux is pretty low (close to 0 but not quite). That's why I think committing builds.zip from my branch, running tests and recommitting builds.zip from unity-staging (or unity-master?) branch would be an overkill. But let me know if you think I should still do that.

**Comment by joshpeterson** [comment]
I don't understand the risk, so as long as you and @Tak agree that the risk is low enough to move forward, I'm fine without separate tests. We'll run ABV on this change before it lands in trunk, so if the necessary tests are in ABV, that is probably good enough.

Generally though we don't worry about committing an extra builds.zip or two, so long as we do it on a branch that won't land in trunk. Usually this is done on a testing-only branch that we close once things are verified.

**Comment by ignas2** [comment]
I guess it's a good idea to create a temporary branch and run the tests there. I'll do that! :)

**Comment by ignas2** [comment]
Ok, so Linux is good. GetAllNetworkInterfacesWork test is somewhat simple but it's hard to test this API extensively on all platforms/configurations.
https://katana.bf.unity3d.com/projects/Unity/builders/proj0-Test%20RegressionRuntimeTests%20-%20Linux32Standalone/builds/1207?unity_branch=platform/android/fixes/ignas/1/tests
https://katana.bf.unity3d.com/projects/Unity/builders/proj0-Test%20RegressionRuntimeTests%20-%20Linux64Standalone/builds/1221?unity_branch=platform/android/fixes/ignas/1/tests

**Comment by joshpeterson** [comment]
Excellent, thanks for testing this.

**Pull request merged**
