### PR TITLE
[Backport From Upstream] Embed Mono LinkerDescription in managed assembly

### PR DESCRIPTION
**Pull request by mderoy**
Prevent stripping types and methods the runtime needs by embedding the link xml directly into the assembly. brought from upstream master. Will fix issues where the runtime trys to access types and methods that have been stripped.

### CODE REVIEW

**Comment by joshpeterson** [comment]
Does our version of the linker understand how to read this link.xml file from the embedded resources?

Also, we already have some linker descriptors that serve this purpose for IL2CPP. Maybe we should confirm that they match with this file.

**Comment by mderoy** [comment]
@joshpeterson I tested and our linker appears to understand these embedded resources. the plan is to use this embedded resource to preserve dependencies on the runtime, and then our linkxml will preserve additional things (if needed)

**Comment by joshpeterson** [comment]
Maybe we should remove our linker descriptors for IL2CPP then. That way we would have only one place we preserve types needed by the runtime.

**Comment by mderoy** [comment]
I think our decision was to maintain a separate file rather than deal with merges in mono

**Comment by mderoy** [comment]
IL2CPP and Linker Changes
https://bitbucket.org/Unity-Technologies/il2cpp/pull-requests/1085/process-embedded-linker-xmls-from/diff

**Pull request merged**
