### PR TITLE
Make unity profile match 2.0/3.5 public keys rather than silverlight

### PR DESCRIPTION
**Pull request by joncham**
Don't merge yet. Asking for feedback.

We already use this branch to compile against as reference assemblies since upstream Mono C# compiler is more strict.

### CODE REVIEW

**Comment by joncham** [comment]
Also, not sure why all these commits are in there.

**Comment by joncham** [comment]
I can create a new branch and apply diff for cleaner history.

**Comment by joshpeterson** [comment]
Agreed, I think a cleaner history would be better.

**Comment by joncham** [comment]
Opened a clean PR here https://github.com/Unity-Technologies/mono/pull/414

**Pull request closed without merging**
